definitions:
  dto.ListPicturesResponse:
    properties:
      count:
        type: integer
      pictures:
        items:
          $ref: '#/definitions/dto.PictureResponse'
        type: array
      total_pages:
        type: integer
    type: object
  dto.PictureResponse:
    properties:
      content_type:
        type: string
      created_on:
        type: string
      height:
        type: integer
      id:
        type: integer
      name:
        type: string
      size:
        type: string
      updated_on:
        type: string
      url:
        type: string
      width:
        type: integer
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: List of pictures along with its metadata
      parameters:
      - description: page number starting from 1
        format: number
        in: query
        name: page
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ListPicturesResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: list of pictures
  /picture/{id}/image:
    get:
      description: Get a specified image file by its ID
      parameters:
      - description: Image Id
        in: path
        name: id
        required: true
        type: number
      responses:
        "200":
          description: OK
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema: {}
      summary: get a image
swagger: "2.0"
