definitions:
  dto.ListPicturesResponse:
    properties:
      pictures:
        items:
          $ref: '#/definitions/dto.PictureResponse'
        type: array
    type: object
  dto.PictureResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: List of pictures along with its metadata
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ListPicturesResponse'
        "500":
          description: Internal Server Error
          schema: {}
      summary: list of pictures
  /picture/{id}/image:
    get:
      description: Get a specified image file by its ID
      parameters:
      - description: Image Id
        in: path
        name: id
        required: true
        type: number
      responses:
        "200":
          description: OK
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema: {}
      summary: get a image
swagger: "2.0"
